#ifndef VIGILANTE_GAMECLOCK_H
#define VIGILANTE_GAMECLOCK_H

#define SECOND_IN_MILLISECONDS 1000.f
#define FPS 60
#define FRAME_TIME_MILLISECONDS (float(SECOND_IN_MILLISECONDS / FPS))
#define MAX_DELTA_TIME_MILLISECONDS 0.05f

#endif //VIGILANTE_GAMECLOCK_H
